[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
either = "1.6.1"
futures = "0.3"
futures-timer = "2"
hyper = "0.14.20" 
hyper-rustls = { version = "0.23.0", features = ["http2"] }
libp2p = { version = "0.46.1", default-features = false, features = ["dcutr", "dns-async-std", "identify", "noise", "relay", "ping", "tcp-async-io", "yamux"] }
log = "0.4"
prost = "0.9"
clap = { version = "3.1.6", features = ["derive"]}
rustls = { version = "0.20.6", features = ["dangerous_configuration"] }
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tonic = { version = "0.6", features = ["tls"] }

[build-dependencies]
tonic-build = "0.6"
